export interface RegistroHora {
    idRegistroHora?:string
    idConvenio?:string
    fechaEntrada?:string
    fechaSalida?:string
    yearEntrada?:string
    monthEntrada?:string
    dayEntrada?:string
    horaEntrada?:string
    minutoEntrada?:string
    segundoEntrada?:string
    yearSalida?:string
    monthSalida?:string
    daySalida?:string
    horaSalida?:string
    minutoSalida?:string
    segundoSalida?:string
    observacionRegistroHora?:string
    aprobadoRegistroHora?
    estadoRegistroHora?:string
    aprobadoFinanzas?:string
    idPersona?:string
    primerNombre?:string
    segundoNombre?:string
    primerApellido?:string
    segundoApellido?:string
    nombreDepartamento?:string
    nombreArea?:string
  }
  